### ISSUE TITLE
Use as standard table data-source instead JSON

### ISSUE THREAD

**Issue by montyclt** [OWOX/brainy-table#19]
Hi,

Can I use this component as stantandard table with th, tr and td without using JSON as data source?

This is because I'm doing server-rendering and not SPA application. I prefer render table from server.

**Comment by web-padawan** [comment]
Actually there are two issues:

1. A server side rendering (SSR) is hard to implement for Polymer elements, mostly because of work required to build Shadow DOM tree. See also related [issue](https://github.com/Polymer/polymer/issues/3955)

2. Anyway, `brainy-table` uses benefits of flex layout and cannot be easily rewritten because of stuff like row details. AFAIK, [vaadin-grid](https://github.com/vaadin/vaadin-grid) in 2.0 version is built with that conception, though. So I'd recommend to consider using that element. For our project,`vaadin-grid`it is a lot more complicated than we need.

**Comment by montyclt** [comment]
Finally, I think I will use this: https://www.npmjs.com/package/html-table-to-json
